# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"foo": "00_acs_pull.ipynb"}

modules = ["acs.py"]

doc_url = "https://cywujeremy.github.io/acs_etl/"

git_url = "https://github.com/cywujeremy/acs_etl/tree/master/"

def custom_doc_links(name): return None
