# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ACS_Blockgroup_Data_Pull": "00_acs_pull.ipynb",
         "database_connector": "01_load.ipynb",
         "series_to_tuple_like_string": "01_load.ipynb",
         "ACS_Blockgroup_Data_Loader": "01_load.ipynb"}

modules = ["acs.py",
           "load.py"]

doc_url = "https://cywujeremy.github.io/acs_etl/"

git_url = "https://github.com/cywujeremy/acs_etl/tree/master/"

def custom_doc_links(name): return None
