# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_acs_pull.ipynb (unless otherwise specified).

__all__ = ['foo', 'foo']

# Cell
def foo():
    print('hello world!')

# Cell
def foo():
    print('hello world!')